- alias: DavidPearce
  label: Person
  relationship:
    object: Transhumanism
    predicate: AFFILIATED_WITH
- alias: HedonisticImperative
  label: Field
  relationship:
    - object: DavidPearce
      predicate: CREATED_BY
    - object: smartDrugs
      predicate: FOCUS_ON
- alias: Singularitianism
  label: Field
  relationship:
    object: Transhumanism
    predicate: PART_OF
- alias: Philosophy
  label: Field
- alias: LibertarianTranshumanism
  label: Field
  relationship:
    object: Transhumanism
    predicate: PART_OF
- alias: DemocraticTranshumanism
  label: Field
  relationship:
    object: Transhumanism
    predicate: PART_OF
- alias: Extropianism
  label: Field
  relationship:
    - object: Transhumanism
      predicate: PART_OF
    - object: Philosophy
      predicate: FOCUS_ON
    - object: MaxMore
      predicate: CREATED_BY
- alias: Posthumanism
  label: Field
  relationship:
    object: Postmodernism
    predicate: DEVELOPED_FROM
- alias: Humanism
  label: Field
  relationship:
    object: Antropocentrism
    predicate: FOCUS_ON
- alias: Antropocentrism
  label: Field
  relationship:
    object: Posthumanism
    predicate: REJECTED_BY
- alias: Dualism
  label: Field
- alias: CriticalPosthumanism
  label: Field
  relationship:
    object: Posthumanism
    predicate: PART_OF
- alias: CulturalPosthumanism
  label: Field
  relationship:
    - object: Posthumanism
      predicate: PART_OF
    - object: AManifestoForCyborgs
      predicate: DEVELOPED_FROM
    - object: LiteraryCriticism
      predicate: DEVELOPED_FROM
    - object: CulturalStudies
      predicate: PART_OF
    - object: AManifestoForCyborgs
      predicate: DEVELOPED_FROM
- alias: PhilosophicalPosthumanism
  label: Field
  relationship:
    object: Posthumanism
    predicate: PART_OF
- alias: LiteraryCriticism
  label: Field
- alias: LiteraryTheory
  label: Field
- alias: CulturalStudies
  label: Field
- alias: AnimalStudies
  label: Field
  relationship:
    object: AManifestoForCyborgs
    predicate: DEVELOPED_FROM
- alias: Transhumanism
  label: Field
  relationship:
    - object: LaDivinaComedia
      predicate: COINED_BY
    - object: TheCocktailParty
      predicate: COINED_BY
    - object: TheEssenseOfTheDemocraticIdea
      predicate: COINED_BY
    - object: Enlightenment
      predicate: FOCUS_ON
- alias: Antihumanism
  label: Field
- alias: Metahumanism
  label: Field
- alias: Posthumanities
  label: Field
- alias: Metahumanities
  label: Field
- alias: ObjectOrientedOntologies
  label: Field
  name: Object-Oriented Ontologies
- alias: NonHumanTurn
  label: Field
  name: Non-human Turn
- alias: Feminism
  label: Field
- alias: JamesHughes
  label: Person
  relationship:
    object: DemocraticTranshumanism
    predicate: AFFILIATED_WITH
- alias: MaxMore
  label: Person
  relationship:
    object: Extropianism
    predicate: AFFILIATED_WITH
- alias: ZoltanIstvan
  from: USA
  label: Person
  relationship:
    - object: LibertarianTranshumanism
      predicate: AFFILIATED_WITH
    - context: run for presidency to attract attention to Transhumanism
      object: PresidencyOfUSA
      predicate: CHALLENGED
- alias: IhabHassan
  label: Person
- alias: DonnaHaraway
  label: Person
- alias: KatherineHayles
  label: Person
- alias: AlhieriDante
  attributes:
    from: Italy
    yob: 1265
    yod: 1321
  label: Person
- alias: TSEliot
  attributes:
    from:
      - UK
      - USA
    name: T.S. Eliot
    yob: 1888
    yod: 1965
  label: Person
- alias: PierreTeilharddeChardin
  attributes:
    from: France
    name: Pierre Teilhard de Chardin
    yob: 1887
    yod: 1955
  label: Person
- alias: JulianHuxley
  attributes:
    from: UK
    yob: 1887
    yod: 1963
  label: Person
  relationship:
    object: PierreTeilharddeChardin
    predicate: INSPIRED_BY
- alias: AldousHuxley
  attributes:
    from: UK
    yob: 1894
    yod: 1963
  label: Person
  relationship:
    attributes:
      position: brother
    object: JulianHuxley
    predicate: RELATED_TO
- alias: TranshumanistDeclaration
  label: Media
  relationship:
    object: JamesHughes
    predicate: CREATED_BY
  type: manifesto
- alias: Humanityplus
  attributes:
    type: website
    url: 'https://humanityplus.org/'
  fullName: Humanity+
  label: Media
  relationship:
    object: Transhumanism
    predicate: PART_OF
- alias: TheFutureOfMankind
  attributes:
    published: 1959
    type: anthology
  label: Media
  name: The Future of Mankind
  relationship:
    object: PierreTeilharddeChardin
    predicate: CREATED_BY
- alias: PrometheusAsPerformer
  attributes:
    published: 1977
    type: article
  fullName: 'Prometheus as Performer: Toward a Posthumanist Culture?'
  label: Media
  name: Prometheus as Performer
  relationship:
    object: IhabHassan
    position: author
    predicate: CREATED_BY
- alias: ThePostmodernTurn
  attributes:
    published: 1987
    type: article
  label: Media
  relationship:
    object: IhabHassan
    position: author
    predicate: CREATED_BY
- alias: HowWeBecameVirtualPosthuman
  attributes:
    fullName: 'How We Became Virtual Posthuman: Virtual Bodies in Cybernetics, Literature and Informatics'
    published: 1999
    type: book
  label: Media
  relationship:
    - object: KatherineHayles
      position: author
      predicate: CREATED_BY
    - object: Postmodernism
      predicate: PART_OF
    - object: Feminism
      predicate: PART_OF
- alias: LaDivinaComedia
  attributes:
    lang: Italian
    published: 1321
    type: literature
  label: Media
  relationship:
    attributes:
      position: author
    object: AlhieriDante
    predicate: CREATED_BY
- alias: TheCocktailParty
  attributes:
    published: 1950
    type: literature
  label: Media
  relationship:
    attributes:
      position: author
    object: TSEliot
    predicate: CREATED_BY
- alias: TheEssenseOfTheDemocraticIdea
  attributes:
    fullName: 'The Essence of the Democratic Idea: A Biological approach'
    published: 1949
    type: paper
  label: Media
  name: The Essence of the Democratic Idea
  relationship:
    - object: TheFutureOfMankind
      predicate: PART_OF
    - object: PierreTeilharddeChardin
      predicate: CREATED_BY
- alias: ThePhenomenonOfMan
  attributes:
    published: 1955
    type: book
  label: Media
  name: The Phenomenon of Man
  relationship:
    - object: PierreTeilharddeChardin
      position: author
      predicate: CREATED_BY
    - object: JulianHuxley
      position: introduction
      predicate: CREATED_BY
- alias: AManifestoForCyborgs
  attributes:
    fullName: 'A Manifesto for Cyborgs: Science, Technology, and Social Feminism in 1980s'
    published: 1985
    type: article
  label: Media
  name: A Manifesto for Cyborgs
  relationship:
    object: DonnaHaraway
    position: author
    predicate: CREATED_BY
- alias: Enlightenment
  attributes:
    end: 1789
    start: 1715
  label: Temporality
- alias: PossibilitiesOfHumansNow
  label: Temporality
  name: Antropocene
- alias: PossibilitiesOfPosthumansNow
  attributes:
    start: XXI
  label: Institution
  name: Possibilities of posthumans now
  relationship:
    - context: humans today are able to shift away from antropocentric onto-epistemological approach
      object: Posthumanism
      predicate: REJECTED_BY
    - context: attainable only by transcending beyond biological shell
      object: Transhumanism
      predicate: ACCEPTED_BY
- alias: smartDrugs
  attributes:
    type: cultural
  label: Institution
  name: smart drugs
- alias: PresidencyOfUSA
  attributes:
    type: government
  label: Institution
- alias: ExtropyInstitute
  attributes:
    status: closed
    type: research
  label: Institution
  relationship:
    object: Extropianism
    predicate: PART_OF